version: '3'
services:
  scoreboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: Scoreboard/latest
    container_name: scoreboard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 5001:5001
    restart: unless-stopped